services:
  - type: web
    name: camrone-paste
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
